language: python
python:
  - "3.6"

install:
- pip --version

script:
- python --version

before_deploy:
- cp README.md README.txt
- zip obs-sc2-scene-switcher-${TRAVIS_TAG}.zip LICENSE README.md README.txt sc2_scene_switcher.py

deploy:
  - provider: releases
    api_key:
      secure: ${GITHUB_API_KEY}
    file: obs-sc2-scene-switcher-${TRAVIS_TAG}.zip
    skip_cleanup: true
    on:
      tags: true