language: python
python:
  - "3.6"

install:
- pip --version

script:
- python --version

before_deploy:
- cd ..
- tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: "YOUR GITHUB API KEY"
    file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true
    on:
      tags: true